server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: auth
  cloud:
    gateway:
      routes:
        - id: core
          uri: http://localhost/8081
          predicates:
            - Path=/components/**
  main:
    allow-bean-definition-overriding: true

token:
  actiontime: 3600
  secretkey: seapps